codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 85%
        threshold: 5%
        base: auto
    patch:
      default:
        target: 85%
        threshold: 5%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "examples/*"
  - "tests/*"
  - "*/tests/*"
  - "*/test_*"
  - "*_test.py"
  - "setup.py"
  - "conftest.py" 