repos:
  # Ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        args: [--exit-non-zero-on-format]

  # MyPy for type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        args: [--ignore-missing-imports]

  # Vulture for dead code detection
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.14
    hooks:
      - id: vulture
        args: [src/, tests/]

  # Release guardrails check
  - repo: local
    hooks:
      - id: release-guardrails
        name: Release Guardrails Check
        entry: python scripts/check_release_guardrails.py
        language: system
        stages: [pre-commit]
        description: "Check for proper version bumps and changelog updates on release commits"
        always_run: true 