repos:
  # Ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # MyPy for type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        args: [--ignore-missing-imports]

  # Vulture for dead code detection
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.10
    hooks:
      - id: vulture
        args: [src/, tests/, .vulture]

  # Release guardrails check
  - repo: local
    hooks:
      - id: release-guardrails
        name: Release Guardrails Check
        entry: python scripts/check_release_guardrails.py
        language: system
        stages: [commit]
        description: "Check for proper version bumps and changelog updates on release commits"
        always_run: true 