name: CI

on:
  push:
    branches: [ main, "feature/**" ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Build & Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install Hatch
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    
    - name: Run lint
      run: hatch run lint:lint

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install Hatch
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    
    - name: Run type check
      run: hatch run typecheck:typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install Hatch
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    
    - name: Run tests
      run: hatch run test:test

  tox:
    name: Tox (Compatibility)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    
    - name: Run tox
      run: tox -q 