name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'src/**'
      - 'pyproject.toml'
      - '.readthedocs.yml'
  release:
    types: [ published ]

jobs:
  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install -e .

      - name: Build documentation
        run: |
          cd docs
          sphinx-build -b html . _build/html

      - name: Validate documentation
        run: |
          cd docs
          # Check for broken links
          python -m sphinx.ext.linkcheck -b linkcheck _build/html || true
          
          # Check for missing references
          python -m sphinx.ext.intersphinx _build/html || true

      - name: Notify ReadTheDocs
        run: |
          echo "Documentation built successfully"
          echo "ReadTheDocs will automatically rebuild from the repository"
          echo "Documentation URL: https://fapilog.readthedocs.io/"

  # Optional: Deploy to GitHub Pages as backup
  deploy-gh-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: deploy-docs
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install -e .

      - name: Build documentation
        run: |
          cd docs
          sphinx-build -b html . _build/html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 